version: '3.5'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: aiogram-bot
        restart: on-failure
        stdin_open: true
        volumes:
            -   ./src:/app
        depends_on:
            - postgres
        environment:
            API_TOKEN: ${API_TOKEN}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    postgres:
        image: postgres:12-alpine
        restart: on-failure
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data:
